services:
  - type: web
    name: postgres
    env: docker
    dockerfilePath: ""
    plan: free
    autoDeploy: false

  - type: web
    name: redis
    env: docker
    dockerfilePath: ""
    plan: free
    autoDeploy: false

  - type: web
    name: n8n
    env: docker
    dockerfilePath: ""
    plan: free
    autoDeploy: false
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: postgres
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: n8n_db
      - key: DB_POSTGRESDB_USER
        value: n8n_user
      - key: DB_POSTGRESDB_PASSWORD
        value: n8n_user_pass
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "false"

  - type: web
    name: evolution-api
    env: docker
    dockerfilePath: ""
    plan: free
    autoDeploy: false
    envVars:
      - key: AUTHENTICATION_API_KEY
        value: 9P30CB28DRB5
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: DATABASE_CONNECTION_URI
        value: postgres://n8n_user:n8n_user_pass@postgres:5432/n8n_db
      - key: CACHE_REDIS_ENABLED
        value: "true"
      - key: CACHE_REDIS_URI
        value: redis://redis:6379
      - key: CACHE_REDIS_PREFIX_KEY
        value: evolution
      - key: CACHE_LOCAL_ENABLED
        value: "false"
      - key: CONFIG_SESSION_PHONE_VERSION
        value: 2.3000.1023204200
    disk:
      name: evolution-instances-disk
      mountPath: /evolution/instances
      sizeGB: 1
